versionCheck: true

safety:
  fall: true
  void: true
  lava: 30 # unit: second (0 for disable)
  levitation: false # if true, enable safety feature in levitation.
  limit: 0s # Safety protect limit. (unit: [d]ay/[h]our/[m]inute/[s]econd, 0 for unlimited)
  cleanup: 1d12h # Deleted after a specified period of time after logout. (unit: d/h/m/s, 0 for disabled)
  save: 12h # save interval. (unit: d/h/m/s, 0 for only stop)

# If you need keep the game balance, restrict flight.
# This setting enable/disable the permission check, restricts can also be set in detail with permissions.
restrict:
  respawn: true
  world: true # World change
  gamemode: true # GameMode change
  # 'temporary' available for 'levitation' and 'water'.
  # The flight will be re-enabled when the state is cleared.
  levitation: temporary
  # Due to Bukkit's limitations, this feature calls many events.
  # Disable this feature if you need to keep the best performance. (This load is usually not an issue.)
  water: false
  flyspeed: 0.1 # Default: 0.1

# Vault required.
economy:
  enable: false
  price: 500 # per minute price
  server: "" # Server account (Name or UUID, UUID is better.)
  refund: true # true/false/payer (Hint: 'payer' is refund to payer)

notice:
  enable:
    particle:
      type: VILLAGER_HAPPY # false/enum ( https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html )
      count: 10
      offset: { x: 0.5, y: 0.5, z: 0.5 } # Hint: Need space, 'x:0' is invalid, 'x: 0' is valid.
      extra: 0 # extra data (Also known as 'speed')
      global: true # show globally if true, player only if false.
    sound:
      type: BLOCK_BEACON_ACTIVATE # false/enum ( https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html )
      volume: 1.0
      pitch: 1.8
      global: false
  disable:
    particle:
      type: SMOKE_LARGE
      count: 5
      offset: # other format
        x: 0.5
        y: 0.5
        z: 0.5
      extra: 0
      global: true
    sound:
      type: BLOCK_BEACON_DEACTIVATE
      volume: 1.0
      pitch: 1.5
      global: false
  timeout:
    position: subtitle # for suppress chat log. (false/chat/title/actionbar/subtitle)
    second: 30 # Warn before the end of flight. (Unit: second, Must be less than 60, 0 for disabled)
    particle:
      type: FIREWORKS_SPARK
      count: 10
      offset: 0.5 # syntax sugar
      extra: 0.1
      global: true
    sound:
      type: ENTITY_PLAYER_LEVELUP
      volume: 1.0
      pitch: 0.7
      global: false
    title: # unit: seconds
      fadeIn: 0.5
      stay: 28.5
      fadeOut: 1
  payment:
    position: actionbar # for persist flight payment.
    particle:
      type: BUBBLE_POP
      count: 10
      offset: { x: 0.5, y: 0.5, z: 0.5 }
      extra: 0
      global: true
    sound:
      type: BLOCK_BEACON_POWER_SELECT
      volume: 1.0
      pitch: 1.5
      global: false
    title:
      fadeIn: 0.5
      stay: 3.5
      fadeOut: 1

# Multi locale support.
locale:
  enable: true
  default: "en_us"


# Don't touch!
version: 2.1
